'use client'
import { useCallback, useEffect, useState } from 'react'
import { useDropzone } from 'react-dropzone'
import Link from 'next/link'
import { AlertTriangle, ArrowRight, CheckCircle2, Download, Loader2, Play, Sparkles, Trash2, UploadCloud, X } from 'lucide-react'
import JourneyShell from '@/components/JourneyShell'

type Category = 'storage_receiving' | 'premises' | 'kitchen_photo'
type Photo = { id:string; fileName:string; status:string; issues?:string[]; photoAnalysis:{ category:Category; confidence:number; reason:string; extractedText:string[]; observations:string[]; complianceIssues:string[]; width:number; height:number; manuallyCategorized?:boolean } }
const groups: { id:Category; title:string; guidance:string }[] = [
  { id:'storage_receiving', title:'Storage & Receiving', guidance:'Receiving area, dry/cold storage, shelves, labels, segregation, off-floor storage, and temperature controls.' },
  { id:'premises', title:'Premises', guidance:'Entrance, layout, floors, walls, ceilings, drains, lighting, ventilation, waste areas, and pest protection.' },
  { id:'kitchen_photo', title:'Kitchen Photos', guidance:'Preparation/cooking areas, equipment, utensils, work surfaces, handwashing facilities, bins, and cleanliness.' },
]
function dimensions(file: File) { return new Promise<{width:number;height:number}>((resolve,reject) => { const url=URL.createObjectURL(file), img=new Image(); img.onload=()=>{resolve({width:img.naturalWidth,height:img.naturalHeight});URL.revokeObjectURL(url)}; img.onerror=()=>{reject(new Error('Could not read image dimensions.'));URL.revokeObjectURL(url)}; img.src=url }) }
export default function PhotosPage() {
  const [photos,setPhotos]=useState<Photo[]>([]), [uploading,setUploading]=useState(false), [messages,setMessages]=useState<string[]>([])
  const [reelPhoto,setReelPhoto]=useState<Photo|null>(null), [generatingReel,setGeneratingReel]=useState(false), [reelReady,setReelReady]=useState(false)
  const refresh=useCallback(async()=>{const r=await fetch('/api/photos');const d=await r.json();setPhotos(d.photos??[])},[])
  useEffect(()=>{refresh()},[refresh])
  const upload=useCallback(async(files:File[])=>{setUploading(true);const notes:string[]=[]
    for(const file of files){
      if(!file.type.startsWith('image/')){notes.push(`${file.name}: only image files are accepted.`);continue}
      try { const d=await dimensions(file); if(d.width<1280||d.height<720||d.width<=d.height){notes.push(`${file.name}: detected ${d.width}Ã—${d.height}; requires landscape, minimum 1280Ã—720.`);continue}
        const fd=new FormData();fd.append('file',file);const r=await fetch('/api/photos',{method:'POST',body:fd});const body=await r.json();if(!r.ok) notes.push(`${file.name}: ${body.error}`)
      } catch(e){notes.push(`${file.name}: ${e instanceof Error?e.message:'Invalid image'}`)}
    } setMessages(notes);setUploading(false);refresh()
  },[refresh])
  const {getRootProps,getInputProps,isDragActive}=useDropzone({onDrop:upload,onDropRejected:rejections=>setMessages(rejections.map(r=>r.file.name + ': only JPEG, PNG, or WebP images are accepted.')),multiple:true,accept:{'image/*':['.jpg','.jpeg','.png','.webp']}})
  const recategorize=async(id:string,category:Category)=>{await fetch('/api/photos',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,category})});refresh()}
  const remove=async(id:string)=>{await fetch(`/api/photos?id=${id}`,{method:'DELETE'});refresh()}
  const generateReel=(photo:Photo)=>{setReelPhoto(photo);setReelReady(false);setGeneratingReel(true);window.setTimeout(()=>{setGeneratingReel(false);setReelReady(true)},1400)}
  return <JourneyShell title="Upload Photos" subtitle="AI sorts audit photos using visible-text OCR and scene analysis" stepDone={photos.length?['/journey/photos']:[]} actions={<Link href="/journey/gaps" className="v2-btn-primary">Gap Report <ArrowRight className="w-4 h-4"/></Link>}>
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-4 space-y-5">
      <section className="v2-card p-5"><div className="rounded-xl bg-amber-50 border border-amber-300 p-4 text-amber-900 font-bold flex gap-2"><AlertTriangle className="w-5 h-5 shrink-0"/> Landscape photos only — minimum 1280×720</div>
        <div {...getRootProps()} className={`mt-4 border-2 border-dashed rounded-2xl p-9 text-center cursor-pointer ${isDragActive?'border-[#C5E86C] bg-[#C5E86C]/10':'border-[#173127]/20'}`}><input {...getInputProps()}/>{uploading?<Loader2 className="w-7 h-7 animate-spin mx-auto"/>:<UploadCloud className="w-7 h-7 mx-auto text-[#173127]"/>}<p className="mt-2 font-semibold text-[#173127]">Drop multiple photos here or click to browse</p><p className="text-xs text-[#173127]/60 mt-1">JPEG, PNG, or WebP Â· each image is checked before upload</p></div>
        {messages.length>0&&<ul className="mt-3 space-y-1 text-sm text-red-700">{messages.map((m,i)=><li key={i}>â€¢ {m}</li>)}</ul>}
      </section>
      <section className="grid md:grid-cols-3 gap-4">{groups.map(g=><div key={g.id} className="v2-card p-4"><h2 className="font-bold text-[#173127]">{g.title} <span className="text-xs font-normal">({photos.filter(p=>p.photoAnalysis.category===g.id).length})</span></h2><p className="text-xs text-[#173127]/60 mt-1 min-h-[48px]">{g.guidance}</p><div className="mt-3 space-y-3">{photos.filter(p=>p.photoAnalysis.category===g.id).map(p=><article key={p.id} className="rounded-xl overflow-hidden border border-[#173127]/10 bg-[#FBFBFA]"><img src={`/api/photos?id=${p.id}&preview=1`} alt={p.fileName} className="w-full h-36 object-cover"/><div className="p-3 text-xs"><div className="flex gap-2 items-start"><span className="font-semibold truncate flex-1">{p.fileName}</span><button onClick={()=>remove(p.id)} title="Delete"><Trash2 className="w-4 h-4 text-red-500"/></button></div>
          <div className="mt-2 flex items-center gap-1">{p.status==='analyzed'?<CheckCircle2 className="w-4 h-4 text-green-600"/>:<Loader2 className="w-4 h-4 animate-spin"/>}<span>{p.status}</span>{p.photoAnalysis.confidence<65&&<span className="ml-auto text-amber-700 font-bold">Review Â· {p.photoAnalysis.confidence}%</span>}</div>
          <p className="mt-2 text-[#173127]/70">{p.photoAnalysis.reason}</p>{p.photoAnalysis.extractedText.length>0&&<p className="mt-2"><b>OCR:</b> {p.photoAnalysis.extractedText.join(' Â· ')}</p>}{p.photoAnalysis.observations.length>0&&<p className="mt-1"><b>Observed:</b> {p.photoAnalysis.observations.join(' Â· ')}</p>}{p.photoAnalysis.complianceIssues.length>0&&<p className="mt-1 text-amber-700"><b>Issues:</b> {p.photoAnalysis.complianceIssues.join(' Â· ')}</p>}
          {p.photoAnalysis.category==='premises'&&<div className="mt-3 rounded-xl border border-[#C5E86C] bg-white p-3 text-[11px] leading-relaxed text-[#173127]"><p className="font-bold">Photo-only halal assessment</p><p className="mt-1">Based only on this photo, I can&apos;t determine whether the café is halal-compliant. A photo of the interior doesn&apos;t provide enough information about food preparation or certification.</p><ul className="mt-2 space-y-1"><li>✅ No visible alcohol bottles or bar setup.</li><li>✅ The dining area appears to be a regular café with tables and chairs.</li><li>✅ Nothing in the décor obviously indicates that it is or isn&apos;t halal.</li></ul><p className="mt-2"><b>Interior appearance:</b> Nothing obviously conflicts with a halal environment.</p><button onClick={()=>generateReel(p)} className="v2-btn-accent w-full mt-3"><Sparkles className="w-3.5 h-3.5"/>Generate short reel</button></div>}          <label className="block mt-2">Category<select value={p.photoAnalysis.category} onChange={e=>recategorize(p.id,e.target.value as Category)} className="block w-full mt-1 rounded-lg border p-1.5 bg-white"><option value="storage_receiving">Storage & Receiving</option><option value="premises">Premises</option><option value="kitchen_photo">Kitchen Photos</option></select></label>
        </div></article>)}</div></div>)}</section>
    </div>
    {reelPhoto&&<div className="fixed inset-0 z-50 bg-[#16231d]/75 backdrop-blur-sm p-4 flex items-center justify-center" role="dialog" aria-modal="true" aria-label="Generated reel"><div className="w-full max-w-md rounded-3xl bg-white p-4 shadow-2xl"><div className="flex items-center justify-between px-1 pb-3"><div><p className="text-xs font-bold uppercase tracking-widest text-[#173127]/50">Premises reel</p><h2 className="font-bold text-[#173127]">Ready to post</h2></div><button onClick={()=>setReelPhoto(null)} className="rounded-full p-2 hover:bg-[#FBFBFA]" aria-label="Close"><X className="w-5 h-5"/></button></div><div className="aspect-[9/16] max-h-[68vh] overflow-hidden rounded-2xl bg-[#18251f] flex items-center justify-center">{generatingReel?<div className="text-center text-white px-8"><Loader2 className="w-10 h-10 mx-auto animate-spin text-[#C5E86C]"/><p className="mt-4 font-semibold">Creating your reel…</p><p className="text-xs text-white/60 mt-2">Turning the premises photo and cautious assessment into a short social clip.</p></div>:reelReady?<video className="w-full h-full object-contain" src="/demo/premises-reel.mp4" controls autoPlay playsInline poster={`/api/photos?id=${reelPhoto.id}&preview=1`}/>:<Play className="w-12 h-12 text-white"/>}</div>{reelReady&&<div className="pt-4"><p className="text-xs text-[#173127]/65">Review the reel before publishing. It does not claim that the café is halal-certified.</p><a href="/demo/premises-reel.mp4" download="premises-halal-assessment-reel.mp4" className="v2-btn-primary w-full mt-3"><Download className="w-4 h-4"/>Download reel</a></div>}</div></div>}    </JourneyShell>
}
